"""Add user info

Revision ID: 3fa54ddb480f
Revises: f8ed8fb880b3
Create Date: 2025-08-23 12:41:42.730428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa54ddb480f'
down_revision: Union[str, Sequence[str], None] = 'f8ed8fb880b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_infos',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('third_name', sa.String(), nullable=True),
    sa.Column('passport_serial', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_infos_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_infos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_infos')
    # ### end Alembic commands ###
